from typing import TypedDict, Optional, List, Dict, Any
from langgraph.graph import StateGraph, END
from sqlalchemy.orm import Session
from backend.database import SessionLocal
from backend.ai.agents import (
    ProjectProfileAgent,
    KnowledgeGraphAgent,
    KTLevelAgent,
    TopicDecompositionAgent,
    QualityAgent,

)
from backend.services.validation_service import ValidationService

class QualityAgent:
    """Agent 6: Validates generated plan against transition quality and compliance standards."""
    @staticmethod
    def run(db: Session, transition_id: str) -> Dict[str, Any]:
        report = ValidationService.run_full_validation(db, transition_id)
        return {
            "status": "success",
            "quality_status": report.overall_status,
            "quality_score": report.score_percent,
            "passed_checks": report.passed_checks,
            "total_checks": report.total_checks,
            "checks": [c.dict() for c in report.checks],
        }

# LangGraph State Schema
class KTPlannerState(TypedDict):
    transition_id: str
    current_stage: str
    status_message: str
    errors: List[str]

# Graph Node Implementations (Agents inspect & persist directly to SQLite; no plan bloat in graph state)
def node_profile_agent(state: KTPlannerState) -> KTPlannerState:
    db = SessionLocal()
    try:
        ProjectProfileAgent.run(db, state["transition_id"])
        return {
            **state,
            "current_stage": "profile_generated",
            "status_message": "Project Profile extracted and synthesized by Agent 1.",
        }
    except Exception as e:
        return {**state, "errors": state.get("errors", []) + [str(e)]}
    finally:
        db.close()

def node_knowledge_graph_agent(state: KTPlannerState) -> KTPlannerState:
    db = SessionLocal()
    try:
        KnowledgeGraphAgent.run(db, state["transition_id"])
        return {
            **state,
            "current_stage": "hierarchy_generated",
            "status_message": "6-tier Knowledge Hierarchy generated by Agent 2.",
        }
    except Exception as e:
        return {**state, "errors": state.get("errors", []) + [str(e)]}
    finally:
        db.close()

def node_kt_level_agent(state: KTPlannerState) -> KTPlannerState:
    db = SessionLocal()
    try:
        KTLevelAgent.run(db, state["transition_id"])
        return {
            **state,
            "current_stage": "levels_evaluated",
            "status_message": "KT levels (L1/L2/L3) evaluated by Agent 3.",
        }
    except Exception as e:
        return {**state, "errors": state.get("errors", []) + [str(e)]}
    finally:
        db.close()

def node_decomposition_agent(state: KTPlannerState) -> KTPlannerState:
    db = SessionLocal()
    try:
        TopicDecompositionAgent.run(db, state["transition_id"])
        return {
            **state,
            "current_stage": "capacity_balanced",
            "status_message": "Target capacity balanced and decomposed by Agent 4.",
        }
    except Exception as e:
        return {**state, "errors": state.get("errors", []) + [str(e)]}
    finally:
        db.close()

def node_quality_agent(state: KTPlannerState) -> KTPlannerState:
    db = SessionLocal()
    try:
        res = QualityAgent.run(db, state["transition_id"])
        return {
            **state,
            "current_stage": "quality_validated",
            "status_message": f"Quality validated by Agent 6 with score {res['quality_score']}%.",
        }
    except Exception as e:
        return {**state, "errors": state.get("errors", []) + [str(e)]}
    finally:
        db.close()

# Build and Compile LangGraph Workflow
def build_kt_planner_workflow():
    workflow = StateGraph(KTPlannerState)

    workflow.add_node("profile_agent", node_profile_agent)
    workflow.add_node("knowledge_graph_agent", node_knowledge_graph_agent)
    workflow.add_node("kt_level_agent", node_kt_level_agent)
    workflow.add_node("decomposition_agent", node_decomposition_agent)
    workflow.add_node("quality_agent", node_quality_agent)

    workflow.set_entry_point("profile_agent")
    workflow.add_edge("profile_agent", "knowledge_graph_agent")
    workflow.add_edge("knowledge_graph_agent", "kt_level_agent")
    workflow.add_edge("kt_level_agent", "decomposition_agent")
    workflow.add_edge("decomposition_agent", "quality_agent")
    workflow.add_edge("quality_agent", END)

    return workflow.compile()

try:
    from agentic_blueprint import wrap
    kt_planner_app = wrap(build_kt_planner_workflow(), risk_class="low", name="KTPlannerWorkflow")
except Exception:
    kt_planner_app = build_kt_planner_workflow()


